# Generated by Django 6.1.1 on 2026-09-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_settings_usersettings',
        ),
    ]
