# Generated by Django 6.1.1 on 2026-09-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NudgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160)),
                ('category', models.CharField(default='gentle', max_length=30)),
            ],
            options={
                'verbose_name': 'Nudge Template',
                'verbose_name_plural': 'Nudge Templates',
                'db_table': 'nudge_template',
            },
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='pods.pod')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_nudges', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_nudges', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='used_nudges', to='nudges.nudgetemplate')),
            ],
            options={
                'verbose_name': 'Nudge',
                'verbose_name_plural': 'Nudges',
                'db_table': 'nudge_nudge',
            },
        ),
    ]
