# Generated by Django 6.1.1 on 2026-09-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('avatar_color', models.CharField(default='#f28c5b', max_length=7)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('goals', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
