# Generated by Django 6.1.1 on 2026-09-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycheckin',
            options={'verbose_name': 'Daily Check-In', 'verbose_name_plural': 'Daily Check-Ins'},
        ),
        migrations.AlterModelTable(
            name='dailycheckin',
            table='home_dailycheckin',
        ),
    ]
