# Generated by Django 6.1.1 on 2026-09-28 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCareGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='physical', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfcare_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self-Care Goal',
                'verbose_name_plural': 'Self-Care Goals',
                'db_table': 'goal_selfcaregoal',
            },
        ),
        migrations.CreateModel(
            name='DailyGoalCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_completions', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='goals.selfcaregoal')),
            ],
            options={
                'verbose_name': 'Daily Goal Completion',
                'verbose_name_plural': 'Daily Goal Completions',
                'db_table': 'goal_dailycompletion',
                'unique_together': {('goal', 'user', 'date')},
            },
        ),
    ]
